### ISSUE TITLE
AddGameEvents Error

### ISSUE THREAD

**Issue by danmalter** [adamazoulay/nhlscrape#9]
There is an error with the AddGameEvents function with game_id = 2019020951 due to what I think is because of Toronto using emergency goalie, David Ayres.  Ayres is missing roster data for primaryNumber, so the rbind function errors out.

https://statsapi.web.nhl.com/api/v1/game/2019020951/feed/live?site=en_nhl

**Comment by adamazoulay** [comment]
Thanks for pointing this out Dan! I've fixed the issue.
